In [80]:
import numpy as np
import pandas as pd

# 1. Считать в pandas.DataFrame любой источник данных: CSV, JSON, Excel-файл, HTML-таблицу и т.п.

In [83]:
# read csv files
dataset = pd.read_csv('vehicles.csv')

In [82]:
dataset

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,7301591192,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,...,NaN,sedan,NaN,https://images.craigslist.org/00o0o_iiraFnHg8q...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:31-0600
426876,7301591187,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,...,NaN,sedan,red,https://images.craigslist.org/00x0x_15sbgnxCIS...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:29-0600
426877,7301591147,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,...,NaN,hatchback,white,https://images.craigslist.org/00L0L_farM7bxnxR...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:17-0600
426878,7301591140,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,...,NaN,sedan,silver,https://images.craigslist.org/00z0z_bKnIVGLkDT...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:11-0600
426879,7301591129,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,...,NaN,coupe,NaN,https://images.craigslist.org/00Y0Y_lEUocjyRxa...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:07-0600

# 2. Привести описание датасета.

датасет: Used Cars Dataset: https://www.kaggle.com/datasets/austinreese/craigslist-carstrucks-data

Craigslist — это крупнейшая в мире коллекция подержанных автомобилей, выставленных на продажу. Этот набор данных включает в себя все записи о подержанных автомобилях в Соединенных Штатах на Craigslist.
Эти данные содержат практически всю необходимую информацию о продажах автомобилей, которую Craigslist предоставляет, включая такие столбцы, как цена, состояние, производитель, регион и 18 других категорий.

# 3. Выполнить над датафреймом следующие операции:

- .head().
- .describe().
- Считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки).
- Фильтрация строк по диапазону индекса.
- Фильтрация набора данных по какому-либо условию.
- Работа с пропущенными значениями:

    удаление строк с пропущенными значениями;
    
    заполнение пропущенных значений средним значением по колонке.
    
    Если пропущенных значений нет - намеренно их сгенерировать, прибить какие-то куски данных в np.nan.

- Создание нового поля, вычисленного на основе значений других полей:

    через выражение на базе имеющихся колонок;
  
    через DataFrame.apply;

    через Series.apply.

- Сортировка по какому-либо из полей.
- Вычисление нескольких статистик по колонкам (использовать встроенные агрегатные функции - любые на выбор).
- Вывод по какому-либо полю / набору полей числа значений с использованием .value_counts().
- Вывод уникальных значений какой-либо колонки с использованием .unique().
- Удаление текущего индекса, и создание нового индекса на базе новой колонки, которая для этого лучше всего подходит - см. reset_index и set_index.

In [84]:
# возвращает первые n строк, n=5 по-умолчанию
dataset.head(2)

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN

In [85]:
# статистика по числовым признакам
dataset.describe()

,id,price,year,odometer,county,lat,long
count,4.268800e+05,4.268800e+05,425675.000000,4.224800e+05,0.0,420331.000000,420331.000000
mean,7.311487e+09,7.519903e+04,2011.235191,9.804333e+04,NaN,38.493940,-94.748599
std,4.473170e+06,1.218228e+07,9.452120,2.138815e+05,NaN,5.841533,18.365462
min,7.207408e+09,0.000000e+00,1900.000000,0.000000e+00,NaN,-84.122245,-159.827728
25%,7.308143e+09,5.900000e+03,2008.000000,3.770400e+04,NaN,34.601900,-111.939847
50%,7.312621e+09,1.395000e+04,2013.000000,8.554800e+04,NaN,39.150100,-88.432600
75%,7.315254e+09,2.648575e+04,2017.000000,1.335425e+05,NaN,42.398900,-80.832039
max,7.317101e+09,3.736929e+09,2022.000000,1.000000e+07,NaN,82.390818,173.885502

In [86]:
print(dataset.iloc[10, 0])
print("____________________________________________________________")
dataset.iloc[6:9, 2:5]

7218893038
____________________________________________________________

            region                           region_url  price
6    hudson valley  https://hudsonvalley.craigslist.org   1000
7    hudson valley  https://hudsonvalley.craigslist.org  15995
8  medford-ashland       https://medford.craigslist.org   5000

In [87]:
# машины младше 2015 года
dataset[dataset['year'] > 2015]

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
29,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/01212_jjirIWa0y0...,Carvana is the safer way to buy a car During t...,NaN,al,32.590000,-85.480000,2021-05-04T12:31:25-0500
30,7316743432,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00x0x_1y9kIOzGCF...,Carvana is the safer way to buy a car During t...,NaN,al,32.590000,-85.480000,2021-05-04T10:41:31-0500
33,7316304717,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,34590,2016.0,chevrolet,silverado 1500 double,good,6 cylinders,...,NaN,pickup,silver,https://images.craigslist.org/00E0E_iKN07Sh7ou...,Carvana is the safer way to buy a car During t...,NaN,al,32.590000,-85.480000,2021-05-03T12:41:33-0500
34,7316285779,https://auburn.craigslist.org/cto/d/auburn-201...,auburn,https://auburn.craigslist.org,35000,2019.0,toyota,tacoma,excellent,6 cylinders,...,NaN,truck,grey,https://images.craigslist.org/00101_dXoZTH7iVm...,Selling my 2019 Toyota Tacoma TRD Off Road Dou...,NaN,al,32.601300,-85.443974,2021-05-03T12:12:59-0500
35,7316257769,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,29990,2016.0,chevrolet,colorado extended cab,good,6 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,al,32.590000,-85.480000,2021-05-03T11:31:14-0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,7301591192,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,...,NaN,sedan,NaN,https://images.craigslist.org/00o0o_iiraFnHg8q...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:31-0600
426876,7301591187,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,...,NaN,sedan,red,https://images.craigslist.org/00x0x_15sbgnxCIS...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:29-0600
426877,7301591147,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,...,NaN,hatchback,white,https://images.craigslist.org/00L0L_farM7bxnxR...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:17-0600
426878,7301591140,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,...,NaN,sedan,silver,https://images.craigslist.org/00z0z_bKnIVGLkDT...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:11-0600
426879,7301591129,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,...,NaN,coupe,NaN,https://images.craigslist.org/00Y0Y_lEUocjyRxa...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:07-0600

In [89]:
# удаление строк с пропущенными значениями
cleaned_data = dataset.dropna()
cleaned_data

Empty DataFrame
Columns: [id, url, region, region_url, price, year, manufacturer, model, condition, cylinders, fuel, odometer, title_status, transmission, VIN, drive, size, type, paint_color, image_url, description, county, state, lat, long, posting_date]
Index: []

[0 rows x 26 columns]

Произошло удаление всех строк, т.к. в каждой строке присутствовали какие-либо пропущенные значения.

In [90]:
dataset['year']

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
           ...
426875    2019.0
426876    2020.0
426877    2020.0
426878    2018.0
426879    2019.0
Name: year, Length: 426880, dtype: float64

In [91]:
df = pd.read_csv('vehicles.csv')

# Название столбца, который нужно заполнить
column_name = 'year'

# Заполнение пустых значений средним по столбцу
df[column_name].fillna(df[column_name].mean())

0         2011.235191
1         2011.235191
2         2011.235191
3         2011.235191
4         2011.235191
             ...
426875    2019.000000
426876    2020.000000
426877    2020.000000
426878    2018.000000
426879    2019.000000
Name: year, Length: 426880, dtype: float64

Пустые значения из стобца 'year' мы заменили средним значением.

In [99]:
# Через выражение на базе имеющихся колонок
dataset['new_column1'] = dataset['price'] * dataset['year']

# Через DataFrame.apply
dataset['new_column2'] = dataset.apply(lambda row: row['price'] * row['year'], axis=1)


# Через Series.apply
dataset['new_column3'] = dataset['price'].apply(lambda x: x * 2)
dataset[["price", "year", "new_column1", "new_column2", "new_column3"]]

        price    year  new_column1  new_column2  new_column3
0        6000     NaN          NaN          NaN        12000
1       11900     NaN          NaN          NaN        23800
2       21000     NaN          NaN          NaN        42000
3        1500     NaN          NaN          NaN         3000
4        4900     NaN          NaN          NaN         9800
...       ...     ...          ...          ...          ...
426875  23590  2019.0   47628210.0   47628210.0        47180
426876  30590  2020.0   61791800.0   61791800.0        61180
426877  34990  2020.0   70679800.0   70679800.0        69980
426878  28990  2018.0   58501820.0   58501820.0        57980
426879  30590  2019.0   61761210.0   61761210.0        61180

[426880 rows x 5 columns]

In [104]:
# Сортировка по цене от дешевых до дорогих
sorted_data = dataset.sort_values(by='price', ascending=True)
sorted_data.iloc[:, 0:5]

,id,url,region,region_url,price
238806,7314044707,https://hickory.craigslist.org/ctd/d/ford-f150...,hickory / lenoir,https://hickory.craigslist.org,0
238809,7314007104,https://hickory.craigslist.org/ctd/d/bmw-serie...,hickory / lenoir,https://hickory.craigslist.org,0
238811,7313985018,https://hickory.craigslist.org/ctd/d/mercedes-...,hickory / lenoir,https://hickory.craigslist.org,0
238812,7313954860,https://hickory.craigslist.org/ctd/d/bmw-428i-...,hickory / lenoir,https://hickory.craigslist.org,0
238813,7313921228,https://hickory.craigslist.org/ctd/d/mercedes-...,hickory / lenoir,https://hickory.craigslist.org,0
...,...,...,...,...,...
37410,7314052904,https://modesto.craigslist.org/ctd/d/modesto-w...,modesto,https://modesto.craigslist.org,3009548743
257840,7309735768,https://southjersey.craigslist.org/ctd/d/tucka...,south jersey,https://southjersey.craigslist.org,3024942282
91576,7309730903,https://delaware.craigslist.org/ctd/d/newark-a...,delaware,https://delaware.craigslist.org,3024942282
318592,7308056031,https://eugene.craigslist.org/cto/d/florence-2...,eugene,https://eugene.craigslist.org,3736928711
356716,7302445002,https://knoxville.craigslist.org/cto/d/new-mar...,knoxville,https://knoxville.craigslist.org,3736928711

In [105]:
# Вычисление нескольких статистик по колонкам:
mean = dataset['price'].mean()
median = dataset['price'].median()
std_dev = dataset['price'].std()

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 75199.0331873126
Median: 13950.0
Standard Deviation: 12182282.173597954

In [107]:
# Вывод по какому-либо полю / набору полей числа значений с использованием .value_counts():
value_counts = dataset['price'].value_counts()
print(value_counts)

price
0        32895
6995      3169
7995      3129
9995      2867
8995      2837
         ...
12589        1
20887        1
22383        1
17455        1
37121        1
Name: count, Length: 15655, dtype: int64

In [108]:
# Вывод уникальных значений какой-либо колонки с использованием .unique():
unique_values = dataset['price'].unique()
print(unique_values)

[ 6000 11900 21000 ...  6328 19853 17873]

In [115]:
# Удаление текущего индекса, и создание нового индекса на базе новой колонки:
# Удаление текущего индекса
df = pd.read_csv('vehicles.csv')
df.reset_index(drop=True)  # сбрасываем индекс
df

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,7301591192,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,...,NaN,sedan,NaN,https://images.craigslist.org/00o0o_iiraFnHg8q...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:31-0600
426876,7301591187,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,...,NaN,sedan,red,https://images.craigslist.org/00x0x_15sbgnxCIS...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:29-0600
426877,7301591147,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,...,NaN,hatchback,white,https://images.craigslist.org/00L0L_farM7bxnxR...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:17-0600
426878,7301591140,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,...,NaN,sedan,silver,https://images.craigslist.org/00z0z_bKnIVGLkDT...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:11-0600
426879,7301591129,https://wyoming.craigslist.org/ctd/d/atlanta-2...,wyoming,https://wyoming.craigslist.org,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,...,NaN,coupe,NaN,https://images.craigslist.org/00Y0Y_lEUocjyRxa...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:07-0600

In [116]:
# Создание нового индекса на базе новой колонки
df.set_index('url', inplace=True)
df

,id,region,region_url,price,year,manufacturer,model,condition,cylinders,fuel,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
url,,,,,,,,,,,,,,,,,,,,,
https://prescott.craigslist.org/cto/d/prescott-2010-ford-ranger/7222695916.html,7222695916,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
https://fayar.craigslist.org/ctd/d/bentonville-2017-hyundai-elantra-se/7218891961.html,7218891961,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
https://keys.craigslist.org/cto/d/summerland-key-2005-excursion/7221797935.html,7221797935,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
https://worcester.craigslist.org/cto/d/west-brookfield-2002-honda-odyssey-ex/7222270760.html,7222270760,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
https://greensboro.craigslist.org/cto/d/trinity-1965-chevrolet-truck/7210384030.html,7210384030,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
https://wyoming.craigslist.org/ctd/d/atlanta-2019-nissan-maxima-sedan-4d/7301591192.html,7301591192,wyoming,https://wyoming.craigslist.org,23590,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,...,NaN,sedan,NaN,https://images.craigslist.org/00o0o_iiraFnHg8q...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:31-0600
https://wyoming.craigslist.org/ctd/d/atlanta-2020-volvo-s60-t5-momentum/7301591187.html,7301591187,wyoming,https://wyoming.craigslist.org,30590,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,...,NaN,sedan,red,https://images.craigslist.org/00x0x_15sbgnxCIS...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:29-0600
https://wyoming.craigslist.org/ctd/d/atlanta-2020-caddy-cadillac-xt4-sport/7301591147.html,7301591147,wyoming,https://wyoming.craigslist.org,34990,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,...,NaN,hatchback,white,https://images.craigslist.org/00L0L_farM7bxnxR...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:17-0600
https://wyoming.craigslist.org/ctd/d/atlanta-2018-lexus-es-es-350-sedan-4d/7301591140.html,7301591140,wyoming,https://wyoming.craigslist.org,28990,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,...,NaN,sedan,silver,https://images.craigslist.org/00z0z_bKnIVGLkDT...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:11-0600
https://wyoming.craigslist.org/ctd/d/atlanta-2019-bmw-series-430i-gran-coupe/7301591129.html,7301591129,wyoming,https://wyoming.craigslist.org,30590,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,...,NaN,coupe,NaN,https://images.craigslist.org/00Y0Y_lEUocjyRxa...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:07-0600

# 4. Продемонстрировать работу .groupby, на основе группировок в groupby вычислить агрегатные функции по одной или нескольким колонкам.

In [123]:
dataset = pd.read_csv('vehicles.csv')
grouped_data = dataset.groupby('region').agg({'price': 'mean', 'year': 'mean'})
grouped_data

                               price         year
region
SF bay area             17038.890327  2010.558773
abilene                 42234.085106  2010.549356
akron / canton          92296.112619  2010.104025
albany                  20489.463540  2011.868348
albuquerque             18260.021680  2011.528794
...                              ...          ...
york                    15981.758044  2009.833977
youngstown              52291.024096  2009.542169
yuba-sutter             14987.230681  2011.348598
yuma                    30356.585075  2010.426866
zanesville / cambridge  19432.623003  2013.054313

[404 rows x 2 columns]

Выше посчитаны средний год машин и средняя стоимость машин в каждом регионе.

# 5.Решейпинг данных 1D->2D с использованием .pivot (можно подать на вход результаты агрегатов, полученных ранее с использованием .groupby (сгруппировать по двум полям).

In [149]:
unique_df = dataset.drop_duplicates(subset = 'year') # удаляем повторяющиеся года

pivot_df = unique_df.pivot(index='year', columns='region', values='price')
print(pivot_df)

region  anchorage / mat-su   auburn  bakersfield  bend  billings  birmingham  \
year
NaN                    NaN      NaN          NaN   NaN       NaN         NaN
1900.0                 NaN      NaN          NaN   NaN       NaN         NaN
1901.0                 NaN      NaN          NaN   NaN       NaN         NaN
1902.0                 NaN      NaN          NaN   NaN       NaN         NaN
1903.0                 NaN      NaN          NaN   NaN       NaN         0.0
...                    ...      ...          ...   ...       ...         ...
2018.0                 NaN  27990.0          NaN   NaN       NaN         NaN
2019.0                 NaN  35000.0          NaN   NaN       NaN         NaN
2020.0                 NaN  39590.0          NaN   NaN       NaN         NaN
2021.0                 NaN      NaN          NaN   NaN       NaN     32186.0
2022.0                 NaN      NaN          NaN   NaN       NaN         NaN

region  cape cod / islands  cedar rapids  chico  cincinnati  ...  montgomery  \
year                                                         ...
NaN                    NaN           NaN    NaN         NaN  ...         NaN
1900.0                 NaN           NaN    NaN         NaN  ...         NaN
1901.0                 NaN           NaN    NaN         NaN  ...         NaN
1902.0                 NaN           NaN    NaN         NaN  ...         NaN
1903.0                 NaN           NaN    NaN         NaN  ...         NaN
...                    ...           ...    ...         ...  ...         ...
2018.0                 NaN           NaN    NaN         NaN  ...         NaN
2019.0                 NaN           NaN    NaN         NaN  ...         NaN
2020.0                 NaN           NaN    NaN         NaN  ...         NaN
2021.0                 NaN           NaN    NaN         NaN  ...         NaN
2022.0                 NaN           NaN    NaN         NaN  ...         NaN

region  north dakota  phoenix  portland  prescott  san diego  san luis obispo  \
year
NaN              NaN      NaN       NaN    6000.0        NaN              NaN
1900.0           NaN      NaN       NaN       NaN        NaN              NaN
1901.0           NaN    999.0       NaN       NaN        NaN              NaN
1902.0     1666666.0      NaN       NaN       NaN        NaN              NaN
1903.0           NaN      NaN       NaN       NaN        NaN              NaN
...              ...      ...       ...       ...        ...              ...
2018.0           NaN      NaN       NaN       NaN        NaN              NaN
2019.0           NaN      NaN       NaN       NaN        NaN              NaN
2020.0           NaN      NaN       NaN       NaN        NaN              NaN
2021.0           NaN      NaN       NaN       NaN        NaN              NaN
2022.0           NaN      NaN       NaN       NaN        NaN              NaN

region  tucson  tyler / east TX  western slope
year
NaN        NaN              NaN            NaN
1900.0     NaN              NaN            NaN
1901.0     NaN              NaN            NaN
1902.0     NaN              NaN            NaN
1903.0     NaN              NaN            NaN
...        ...              ...            ...
2018.0     NaN              NaN            NaN
2019.0     NaN              NaN            NaN
2020.0     NaN              NaN            NaN
2021.0     NaN              NaN            NaN
2022.0     NaN              NaN            NaN

[115 rows x 31 columns]

# 6. Решейпинг 1D->2D данных, соединённых с группировкой / агрегацией (одним словом - сводная таблица): .pivot_table. Группировать только по категориальным полям или числовым, если значений немного.

In [129]:
pt = pd.read_csv('vehicles.csv')
pivot_table = pd.pivot_table(pt, values='price', index='year', columns='region', aggfunc=np.mean)
print(pivot_table)

region   SF bay area       abilene  akron / canton        albany  \
year
1900.0           NaN           NaN             NaN           NaN
1901.0           NaN           NaN             NaN           NaN
1902.0           NaN           NaN             NaN           NaN
1903.0           NaN           NaN             NaN           NaN
1905.0           NaN           NaN             NaN           NaN
...              ...           ...             ...           ...
2018.0  23743.853659  30257.071429    27182.680000  30635.054054
2019.0  26958.700405  46306.928571   706128.150685  35926.755725
2020.0  29752.773050  42463.714286    36519.720000  37903.648438
2021.0  29144.066667           NaN    81533.571429  27728.500000
2022.0           NaN           NaN             NaN           NaN

region   albuquerque  altoona-johnstown      amarillo          ames  \
year
1900.0           NaN                NaN           NaN           NaN
1901.0           NaN                NaN           NaN           NaN
1902.0           NaN                NaN           NaN           NaN
1903.0           NaN                NaN           NaN           NaN
1905.0           NaN                NaN           NaN           NaN
...              ...                ...           ...           ...
2018.0  24003.890490       31295.730769  28524.203704  29429.862069
2019.0  25152.471074       34893.600000  32176.000000  31549.000000
2020.0  32735.873626       36891.666667  35675.375000  37472.076923
2021.0  44645.913043       48525.000000           NaN  35191.750000
2022.0           NaN                NaN           NaN           NaN

region  anchorage / mat-su     ann arbor  ...     winchester  winston-salem  \
year                                      ...
1900.0                 NaN           NaN  ...            NaN            NaN
1901.0                 NaN           NaN  ...            NaN            NaN
1902.0                 NaN           NaN  ...            NaN            NaN
1903.0                 NaN           NaN  ...            NaN            NaN
1905.0                 NaN           NaN  ...            NaN            NaN
...                    ...           ...  ...            ...            ...
2018.0        27844.793594  24959.397727  ...   24805.955882   25318.894118
2019.0        32936.063253  30404.869565  ...   28499.488372   30855.390244
2020.0        34937.095238  34973.257576  ...   33175.459459   37049.169811
2021.0        31851.692308    906.417910  ...  135596.666667   44743.333333
2022.0                 NaN           NaN  ...            NaN            NaN

region  worcester / central MA       wyoming        yakima          york  \
year
1900.0                     NaN           NaN           NaN           NaN
1901.0                     NaN           NaN           NaN           NaN
1902.0                     NaN           NaN           NaN           NaN
1903.0                     NaN           NaN           NaN           NaN
1905.0                     NaN           NaN           NaN           NaN
...                        ...           ...           ...           ...
2018.0            27486.956140  27869.153846  27325.842466  27617.093750
2019.0            30192.070588  33646.413793  39637.065421  33250.204545
2020.0            37321.584615  39389.333333  42454.637681  32260.108696
2021.0            19990.000000  65085.000000  45586.222222   9995.000000
2022.0             3500.000000           NaN    431.000000           NaN

region     youngstown   yuba-sutter          yuma  zanesville / cambridge
year
1900.0            NaN           NaN           NaN                     NaN
1901.0            NaN           NaN           NaN                     NaN
1902.0            NaN           NaN           NaN                     NaN
1903.0            NaN           NaN           NaN                     NaN
1905.0            NaN           NaN           NaN                     NaN
...               ...           ...           ...                     ...
2018.0   26546.847826  24510.390476  38379.590909            29288.184211
2019.0  719731.833333  27803.542553  45212.681818            31722.333333
2020.0   34704.523810  30542.500000  60014.772727            35544.827586
2021.0   12500.000000  12649.461538           NaN                     NaN
2022.0            NaN           NaN           NaN                     NaN

[114 rows x 404 columns]

C:\Users\ikasp\AppData\Local\Temp\ipykernel_2364\924267264.py:2: FutureWarning: The provided callable <function mean at 0x00000231CAE1DA80> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_table = pd.pivot_table(pt, values='price', index='year', columns='region', aggfunc=np.mean)

# 7. Вычислить квантили распределения какого-либо вещественного признака (с использованием numpy.quantile или nump.percentile).

In [153]:
price_column = dataset["price"]
q1 = np.percentile(price_column, 25)
median = np.percentile(price_column, 50)
q3 = np.percentile(price_column, 75)
print("Первый квантиль:", q1)
print("Медиана:", median)
print("Третий квантиль:", q3)

Первый квантиль: 5900.0
Медиана: 13950.0
Третий квантиль: 26485.75

# 8. Вычислить (в виде текста) гистограмму какого-либо вещественного признака (с использованием numpy.histogram). Значения гистограммы можно использовать в качестве загрубленного числового признака для заданий (5) или (6).

In [155]:
hist, bins = np.histogram(dataset['price'], bins=10)
print("Histogram:")
for i in range(len(hist)):
    print(f"{bins[i]} - {bins[i+1]}: {hist[i]}")

Histogram:
0.0 - 373692871.1: 426869
373692871.1 - 747385742.2: 0
747385742.2 - 1121078613.3000002: 4
1121078613.3000002 - 1494771484.4: 2
1494771484.4 - 1868464355.5: 0
1868464355.5 - 2242157226.6000004: 0
2242157226.6000004 - 2615850097.7000003: 0
2615850097.7000003 - 2989542968.8: 0
2989542968.8 - 3363235839.9: 3
3363235839.9 - 3736928711.0: 2

# 9. Проитерировать DataFrame построчно .iterrows() и выполнить какую-либо операцию внутри цикла.

In [166]:
data_iter = dataset.iloc[27:35]
for index, row in data_iter.iterrows():
    print(f"Row: {index}")
    print(f"Region: {row['region']}, Price: {row['price']}, Year: {row['year']}")
    new_price = row['price'] * 2 # увеличим стоимость машины
    print(f"New price for row {index}: {new_price}\n")

Row: 27
Region: auburn, Price: 33590, Year: 2014.0
New price for row 27: 67180

Row: 28
Region: auburn, Price: 22590, Year: 2010.0
New price for row 28: 45180

Row: 29
Region: auburn, Price: 39590, Year: 2020.0
New price for row 29: 79180

Row: 30
Region: auburn, Price: 30990, Year: 2017.0
New price for row 30: 61980

Row: 31
Region: auburn, Price: 15000, Year: 2013.0
New price for row 31: 30000

Row: 32
Region: auburn, Price: 27990, Year: 2012.0
New price for row 32: 55980

Row: 33
Region: auburn, Price: 34590, Year: 2016.0
New price for row 33: 69180

Row: 34
Region: auburn, Price: 35000, Year: 2019.0
New price for row 34: 70000

# 10. Получить DataFrame с MultiIndex любым способом: через конструктор (в документации есть множество видов конструкторов для создания MultiIndex с нуля), через read_sql / read_csv / read_excel, read_*, через pivot_table, через groupby или иными способами.

In [168]:
data_multi = dataset.copy()
data_multi["price"] = data_multi["price"].astype('category')
data_multi.set_index(keys=['price', 'region'], append=True, inplace=True)# Устанавливаем мультииндекс
data_multi.head(10)

,,,id,url,region_url,year,manufacturer,model,condition,cylinders,fuel,odometer,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
,price,region,,,,,,,,,,,,,,,,,,,,,
0,6000,prescott,7222695916,https://prescott.craigslist.org/cto/d/prescott...,https://prescott.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,11900,fayetteville,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,https://fayar.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,21000,florida keys,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,https://keys.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,1500,worcester / central MA,7222270760,https://worcester.craigslist.org/cto/d/west-br...,https://worcester.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,4900,greensboro,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,https://greensboro.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
5,1600,hudson valley,7222379453,https://hudsonvalley.craigslist.org/cto/d/west...,https://hudsonvalley.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ny,NaN,NaN,NaN
6,1000,hudson valley,7221952215,https://hudsonvalley.craigslist.org/cto/d/west...,https://hudsonvalley.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ny,NaN,NaN,NaN
7,15995,hudson valley,7220195662,https://hudsonvalley.craigslist.org/cto/d/poug...,https://hudsonvalley.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ny,NaN,NaN,NaN
8,5000,medford-ashland,7209064557,https://medford.craigslist.org/cto/d/grants-pa...,https://medford.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,or,NaN,NaN,NaN
9,3000,erie,7219485069,https://erie.craigslist.org/cto/d/erie-2012-su...,https://erie.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,pa,NaN,NaN,NaN

In [169]:
data_multi.swaplevel('region', 'price')

,,,id,url,region_url,year,manufacturer,model,condition,cylinders,fuel,odometer,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
,region,price,,,,,,,,,,,,,,,,,,,,,
0,prescott,6000,7222695916,https://prescott.craigslist.org/cto/d/prescott...,https://prescott.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,fayetteville,11900,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,https://fayar.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,florida keys,21000,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,https://keys.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,worcester / central MA,1500,7222270760,https://worcester.craigslist.org/cto/d/west-br...,https://worcester.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,greensboro,4900,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,https://greensboro.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426875,wyoming,23590,7301591192,https://wyoming.craigslist.org/ctd/d/atlanta-2...,https://wyoming.craigslist.org,2019.0,nissan,maxima s sedan 4d,good,6 cylinders,gas,32226.0,...,NaN,sedan,NaN,https://images.craigslist.org/00o0o_iiraFnHg8q...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:31-0600
426876,wyoming,30590,7301591187,https://wyoming.craigslist.org/ctd/d/atlanta-2...,https://wyoming.craigslist.org,2020.0,volvo,s60 t5 momentum sedan 4d,good,NaN,gas,12029.0,...,NaN,sedan,red,https://images.craigslist.org/00x0x_15sbgnxCIS...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:29-0600
426877,wyoming,34990,7301591147,https://wyoming.craigslist.org/ctd/d/atlanta-2...,https://wyoming.craigslist.org,2020.0,cadillac,xt4 sport suv 4d,good,NaN,diesel,4174.0,...,NaN,hatchback,white,https://images.craigslist.org/00L0L_farM7bxnxR...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:17-0600
426878,wyoming,28990,7301591140,https://wyoming.craigslist.org/ctd/d/atlanta-2...,https://wyoming.craigslist.org,2018.0,lexus,es 350 sedan 4d,good,6 cylinders,gas,30112.0,...,NaN,sedan,silver,https://images.craigslist.org/00z0z_bKnIVGLkDT...,Carvana is the safer way to buy a car During t...,NaN,wy,33.786500,-84.445400,2021-04-04T03:21:11-0600
426879,wyoming,30590,7301591129,https://wyoming.craigslist.org/ctd/d/atlanta-2...,https://wyoming.craigslist.org,2019.0,bmw,4 series 430i gran coupe,good,NaN,gas,22716.0,...,NaN,coupe,NaN,https://images.craigslist.org/00Y0Y_lEUocjyRxa...,Carvana is the safer way to buy a car During t...,NaN,wy,33.779214,-84.411811,2021-04-04T03:21:07-0600

In [170]:
print(data_multi.transpose().head(10))

                                                         0       \
price                                                      6000
region                                                 prescott
id                                                   7222695916
url           https://prescott.craigslist.org/cto/d/prescott...
region_url                      https://prescott.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         1       \
price                                                     11900
region                                             fayetteville
id                                                   7218891961
url           https://fayar.craigslist.org/ctd/d/bentonville...
region_url                         https://fayar.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         2       \
price                                                     21000
region                                             florida keys
id                                                   7221797935
url           https://keys.craigslist.org/cto/d/summerland-k...
region_url                          https://keys.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         3       \
price                                                      1500
region                                   worcester / central MA
id                                                   7222270760
url           https://worcester.craigslist.org/cto/d/west-br...
region_url                     https://worcester.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         4       \
price                                                      4900
region                                               greensboro
id                                                   7210384030
url           https://greensboro.craigslist.org/cto/d/trinit...
region_url                    https://greensboro.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         5       \
price                                                      1600
region                                            hudson valley
id                                                   7222379453
url           https://hudsonvalley.craigslist.org/cto/d/west...
region_url                  https://hudsonvalley.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         6       \
price                                                      1000
region                                            hudson valley
id                                                   7221952215
url           https://hudsonvalley.craigslist.org/cto/d/west...
region_url                  https://hudsonvalley.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         7       \
price                                                     15995
region                                            hudson valley
id                                                   7220195662
url           https://hudsonvalley.craigslist.org/cto/d/poug...
region_url                  https://hudsonvalley.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         8       \
price                                                      5000
region                                          medford-ashland
id                                                   7209064557
url           https://medford.craigslist.org/cto/d/grants-pa...
region_url                       https://medford.craigslist.org
year                                                        NaN
manufacturer                                                NaN
model                                                       NaN
condition                                                   NaN
cylinders                                                   NaN
fuel                                                        NaN
odometer                                                    NaN

                                                         9       ...  \
price                                                      3000  ...
region                                                     erie  ...
id                                                   7219485069  ...
url           https://erie.craigslist.org/cto/d/erie-2012-su...  ...
region_url                          https://erie.craigslist.org  ...
year                                                        NaN  ...
manufacturer                                                NaN  ...
model                                                       NaN  ...
condition                                                   NaN  ...
cylinders                                                   NaN  ...
fuel                                                        NaN  ...
odometer                                                    NaN  ...

                                                         426870  \
price                                                     22990
region                                                  wyoming
id                                                   7301592119
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2020.0
manufacturer                                            hyundai
model                                        sonata se sedan 4d
condition                                                  good
cylinders                                                   NaN
fuel                                                        gas
odometer                                                 3066.0

                                                         426871  \
price                                                     17990
region                                                  wyoming
id                                                   7301591639
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2018.0
manufacturer                                                kia
model                              sportage lx sport utility 4d
condition                                                  good
cylinders                                                   NaN
fuel                                                        gas
odometer                                                34239.0

                                                         426872  \
price                                                     32590
region                                                  wyoming
id                                                   7301591201
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2020.0
manufacturer                                      mercedes-benz
model                                             c-class c 300
condition                                                  good
cylinders                                                   NaN
fuel                                                        gas
odometer                                                19059.0

                                                         426873  \
price                                                     30990
region                                                  wyoming
id                                                   7301591202
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2018.0
manufacturer                                      mercedes-benz
model                                             glc 300 sport
condition                                                  good
cylinders                                                   NaN
fuel                                                        gas
odometer                                                15080.0

                                                         426874  \
price                                                     33590
region                                                  wyoming
id                                                   7301591199
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2018.0
manufacturer                                              lexus
model                                           gs 350 sedan 4d
condition                                                  good
cylinders                                           6 cylinders
fuel                                                        gas
odometer                                                30814.0

                                                         426875  \
price                                                     23590
region                                                  wyoming
id                                                   7301591192
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2019.0
manufacturer                                             nissan
model                                         maxima s sedan 4d
condition                                                  good
cylinders                                           6 cylinders
fuel                                                        gas
odometer                                                32226.0

                                                         426876  \
price                                                     30590
region                                                  wyoming
id                                                   7301591187
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2020.0
manufacturer                                              volvo
model                                  s60 t5 momentum sedan 4d
condition                                                  good
cylinders                                                   NaN
fuel                                                        gas
odometer                                                12029.0

                                                         426877  \
price                                                     34990
region                                                  wyoming
id                                                   7301591147
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2020.0
manufacturer                                           cadillac
model                                          xt4 sport suv 4d
condition                                                  good
cylinders                                                   NaN
fuel                                                     diesel
odometer                                                 4174.0

                                                         426878  \
price                                                     28990
region                                                  wyoming
id                                                   7301591140
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2018.0
manufacturer                                              lexus
model                                           es 350 sedan 4d
condition                                                  good
cylinders                                           6 cylinders
fuel                                                        gas
odometer                                                30112.0

                                                         426879
price                                                     30590
region                                                  wyoming
id                                                   7301591129
url           https://wyoming.craigslist.org/ctd/d/atlanta-2...
region_url                       https://wyoming.craigslist.org
year                                                     2019.0
manufacturer                                                bmw
model                                  4 series 430i gran coupe
condition                                                  good
cylinders                                                   NaN
fuel                                                        gas
odometer                                                22716.0

[10 rows x 426880 columns]

In [172]:
data_multi.droplevel('region').head(10)

,,id,url,region_url,year,manufacturer,model,condition,cylinders,fuel,odometer,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
,price,,,,,,,,,,,,,,,,,,,,,
0,6000,7222695916,https://prescott.craigslist.org/cto/d/prescott...,https://prescott.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,11900,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,https://fayar.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,21000,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,https://keys.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,1500,7222270760,https://worcester.craigslist.org/cto/d/west-br...,https://worcester.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,4900,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,https://greensboro.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN
5,1600,7222379453,https://hudsonvalley.craigslist.org/cto/d/west...,https://hudsonvalley.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ny,NaN,NaN,NaN
6,1000,7221952215,https://hudsonvalley.craigslist.org/cto/d/west...,https://hudsonvalley.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ny,NaN,NaN,NaN
7,15995,7220195662,https://hudsonvalley.craigslist.org/cto/d/poug...,https://hudsonvalley.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ny,NaN,NaN,NaN
8,5000,7209064557,https://medford.craigslist.org/cto/d/grants-pa...,https://medford.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,or,NaN,NaN,NaN
9,3000,7219485069,https://erie.craigslist.org/cto/d/erie-2012-su...,https://erie.craigslist.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,pa,NaN,NaN,NaN

# 11. Продемонстировать работу .merge.

In [173]:
new_data = pd.read_csv('vehicles.csv')
data_1 = new_data.iloc[27:32]
data_2 = new_data.iloc[32:37]

In [175]:
data_1

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
27,7316814884,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,33590,2014.0,gmc,sierra 1500 crew cab slt,good,8 cylinders,...,NaN,pickup,white,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,NaN,al,32.590,-85.4800,2021-05-04T12:31:18-0500
28,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,...,NaN,pickup,blue,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,NaN,al,32.590,-85.4800,2021-05-04T12:31:08-0500
29,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/01212_jjirIWa0y0...,Carvana is the safer way to buy a car During t...,NaN,al,32.590,-85.4800,2021-05-04T12:31:25-0500
30,7316743432,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00x0x_1y9kIOzGCF...,Carvana is the safer way to buy a car During t...,NaN,al,32.590,-85.4800,2021-05-04T10:41:31-0500
31,7316356412,https://auburn.craigslist.org/cto/d/auburn-uni...,auburn,https://auburn.craigslist.org,15000,2013.0,ford,f-150 xlt,excellent,6 cylinders,...,full-size,truck,black,https://images.craigslist.org/00404_l4loxHvdQe...,2013 F-150 XLT V6 4 Door. Good condition. Leve...,NaN,al,32.592,-85.5189,2021-05-03T14:02:03-0500

In [176]:
data_2

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
32,7316343444,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,27990,2012.0,gmc,sierra 2500 hd extended cab,good,8 cylinders,...,NaN,pickup,black,https://images.craigslist.org/00V0V_ftJbKrOgdi...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T13:41:25-0500
33,7316304717,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,34590,2016.0,chevrolet,silverado 1500 double,good,6 cylinders,...,NaN,pickup,silver,https://images.craigslist.org/00E0E_iKN07Sh7ou...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T12:41:33-0500
34,7316285779,https://auburn.craigslist.org/cto/d/auburn-201...,auburn,https://auburn.craigslist.org,35000,2019.0,toyota,tacoma,excellent,6 cylinders,...,NaN,truck,grey,https://images.craigslist.org/00101_dXoZTH7iVm...,Selling my 2019 Toyota Tacoma TRD Off Road Dou...,NaN,al,32.6013,-85.443974,2021-05-03T12:12:59-0500
35,7316257769,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,29990,2016.0,chevrolet,colorado extended cab,good,6 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T11:31:14-0500
36,7316133914,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,38590,2011.0,chevrolet,corvette grand sport,good,8 cylinders,...,NaN,other,red,https://images.craigslist.org/00U0U_kKYnS1LWh8...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T07:50:35-0500

In [179]:
pd.merge(data_1, data_2, on='manufacturer', how='inner')

,id_x,url_x,region_x,region_url_x,price_x,year_x,manufacturer,model_x,condition_x,cylinders_x,...,size_y,type_y,paint_color_y,image_url_y,description_y,county_y,state_y,lat_y,long_y,posting_date_y
0,7316814884,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,33590,2014.0,gmc,sierra 1500 crew cab slt,good,8 cylinders,...,NaN,pickup,black,https://images.craigslist.org/00V0V_ftJbKrOgdi...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T13:41:25-0500
1,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,...,NaN,pickup,silver,https://images.craigslist.org/00E0E_iKN07Sh7ou...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T12:41:33-0500
2,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T11:31:14-0500
3,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,...,NaN,other,red,https://images.craigslist.org/00U0U_kKYnS1LWh8...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T07:50:35-0500
4,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,NaN,pickup,silver,https://images.craigslist.org/00E0E_iKN07Sh7ou...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T12:41:33-0500
5,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T11:31:14-0500
6,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,NaN,other,red,https://images.craigslist.org/00U0U_kKYnS1LWh8...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T07:50:35-0500
7,7316743432,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,...,NaN,truck,grey,https://images.craigslist.org/00101_dXoZTH7iVm...,Selling my 2019 Toyota Tacoma TRD Off Road Dou...,NaN,al,32.6013,-85.443974,2021-05-03T12:12:59-0500

# 12. Продемонстрировать работу с .concat или append.

In [180]:
pd.concat([data_1, data_2])

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
27,7316814884,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,33590,2014.0,gmc,sierra 1500 crew cab slt,good,8 cylinders,...,NaN,pickup,white,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-04T12:31:18-0500
28,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,...,NaN,pickup,blue,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-04T12:31:08-0500
29,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/01212_jjirIWa0y0...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-04T12:31:25-0500
30,7316743432,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00x0x_1y9kIOzGCF...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-04T10:41:31-0500
31,7316356412,https://auburn.craigslist.org/cto/d/auburn-uni...,auburn,https://auburn.craigslist.org,15000,2013.0,ford,f-150 xlt,excellent,6 cylinders,...,full-size,truck,black,https://images.craigslist.org/00404_l4loxHvdQe...,2013 F-150 XLT V6 4 Door. Good condition. Leve...,NaN,al,32.5920,-85.518900,2021-05-03T14:02:03-0500
32,7316343444,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,27990,2012.0,gmc,sierra 2500 hd extended cab,good,8 cylinders,...,NaN,pickup,black,https://images.craigslist.org/00V0V_ftJbKrOgdi...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T13:41:25-0500
33,7316304717,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,34590,2016.0,chevrolet,silverado 1500 double,good,6 cylinders,...,NaN,pickup,silver,https://images.craigslist.org/00E0E_iKN07Sh7ou...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T12:41:33-0500
34,7316285779,https://auburn.craigslist.org/cto/d/auburn-201...,auburn,https://auburn.craigslist.org,35000,2019.0,toyota,tacoma,excellent,6 cylinders,...,NaN,truck,grey,https://images.craigslist.org/00101_dXoZTH7iVm...,Selling my 2019 Toyota Tacoma TRD Off Road Dou...,NaN,al,32.6013,-85.443974,2021-05-03T12:12:59-0500
35,7316257769,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,29990,2016.0,chevrolet,colorado extended cab,good,6 cylinders,...,NaN,pickup,red,https://images.craigslist.org/00N0N_1xMPvfxRAI...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T11:31:14-0500
36,7316133914,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,38590,2011.0,chevrolet,corvette grand sport,good,8 cylinders,...,NaN,other,red,https://images.craigslist.org/00U0U_kKYnS1LWh8...,Carvana is the safer way to buy a car During t...,NaN,al,32.5900,-85.480000,2021-05-03T07:50:35-0500